# Generated by Django 3.2.2 on 2021-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Hname', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Vaccine', 'Vaccine'), ('General-Bed', 'General-Bed'), ('Oxygen-Bed', 'Oxygen-Bed'), ('Bed With-Ventilator', 'Bed With-Ventilator')], max_length=200, null=True)),
                ('available', models.FloatField(null=True)),
                ('text', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
