# Generated by Django 3.2.2 on 2021-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_resources_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='text',
            new_name='add',
        ),
        migrations.AddField(
            model_name='resources',
            name='contact',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
